In [1]:
# Importing libraries
import numpy as np 
import pandas as pd
import os
import glob

In [2]:
# defining dataset location
folder_path = "/Users/jain/Downloads/archive"

In [3]:
csv_files = glob.glob(os.path.join(folder_path, "*.csv"))

In [4]:
#Concatenating data into one dataset 
df_list = []

for file in csv_files:
    df_list.append(pd.read_csv(file))

combined_df = pd.concat(df_list, ignore_index=True)

print(combined_df)

      product_id        title  \
0       18602872      My Room
1       18602850      My Room
2        8961147   Story@home
3        8430275    MYTRIDENT
4       18346118       Arrabi
...          ...          ...
1991    22196594        Zoiro
1992    22196914       Zivame
1993    21906602       bummer
1994    13889998         XYXX
1995    22436508  Bruchi CLUB

                                    product_description  rating  \
0     Yellow & Green Floral 140 TC King Bedsheet wit...     4.7
1     Ethnic Print 144 TC Super King Bedsheet with 2...     4.5
2     Pink & White Floral 160 TC Cotton 1 King Bedsh...     3.7
3     Sea Green Floral Flat 120 TC Cotton 1 Queen Be...     4.4
4     Pink & White Graphic 300 TC King Bedsheet with...     0.0
...                                                 ...     ...
1991          Men Pack Of 2 Anti-Bacterial Basic Briefs     5.0
1992  Women Pack Of 3 Low-Rise Ultra Soft Bikini Briefs     4.6
1993      Women Printed Micro Modal Mid Rise Boy Shorts     4.6
1994  Men Grey Solid Ultra-Soft Antimicrobial Basic ...     4.1
1995           Men Low-Rise Anti-Bacterial Basic Briefs     5.0

      ratings_count  initial_price  discount  final_price currency  \
0                10         2999.0      54.0  "₹2,999.00"      INR
1                22         2999.0      54.0  "₹2,999.00"      INR
2                 7         2199.0      53.0  "₹2,199.00"      INR
3                26         2199.0      46.0  "₹2,199.00"      INR
4                 0         3329.0      74.0    "₹865.00"      INR
...             ...            ...       ...          ...      ...
1991              6          499.0       NaN    "₹499.00"      INR
1992              5          799.0      50.0    "₹399.00"      INR
1993             23          599.0      25.0    "₹449.00"      INR
1994            202          249.0       NaN    "₹249.00"      INR
1995              4          888.0      65.0    "₹310.00"      INR

                                                 images  ...  \
0     http://assets.myntassets.com/assets/images/186...  ...
1     http://assets.myntassets.com/assets/images/186...  ...
2     http://assets.myntassets.com/assets/images/896...  ...
3     http://assets.myntassets.com/assets/images/pro...  ...
4     http://assets.myntassets.com/assets/images/183...  ...
...                                                 ...  ...
1991  http://assets.myntassets.com/assets/images/221...  ...
1992  http://assets.myntassets.com/assets/images/221...  ...
1993  http://assets.myntassets.com/assets/images/219...  ...
1994  http://assets.myntassets.com/assets/images/138...  ...
1995  http://assets.myntassets.com/assets/images/224...  ...

                                        amount_of_stars  \
0     {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...
1     {"1_star":1,"2_stars":1,"3_stars":1,"4_stars":...
2     {"1_star":1,"2_stars":1,"3_stars":0,"4_stars":...
3     {"1_star":0,"2_stars":1,"3_stars":2,"4_stars":...
4     {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...
...                                                 ...
1991  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...
1992  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...
1993  {"1_star":2,"2_stars":0,"3_stars":0,"4_stars":...
1994  {"1_star":15,"2_stars":13,"3_stars":20,"4_star...
1995  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...

                                    what_customers_said  \
0                                                   NaN
1                                                   NaN
2                                                   NaN
3                                                   NaN
4                                                   NaN
...                                                 ...
1991  [{"percentage":"100","value_name":"Fit, Just R...
1992                                                NaN
1993                                                NaN
1994  [{"percentage":"70","value_name":"Fit, Just Ri...
1995  [{"percentage":"100","value_name":"Fit, Just R...

                                  seller_name  \
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                              Sig███Ove███as
...                                       ...
1991           J.G███OSI███ PR█████████ITE███
1992        MIL███AR ███AIL█████████LIM██████
1993        BAL███APP███LS █████████IMI██████
1994  XYX███PPA███S P█████████MIT████████████
1995     BRU███ CL███APP█████████ATE█████████

                                                  sizes  \
0     [{"size":"Single"},{"size":"Double Queen"},{"s...
1                               [{"size":"Super King"}]
2                              [{"size":"Double King"}]
3                             [{"size":"Double Queen"}]
4                               [{"size":"Super King"}]
...                                                 ...
1991  [{"size":"S","value":"28.0in","value_name":"To...
1992  [{"size":"S","value":"28.0in","value_name":"To...
1993  [{"size":"S","value":"28.0in","value_name":"To...
1994  [{"size":"S","value":"28.0in to 30.0in","value...
1995  [{"size":"S","value":"28.0in","value_name":"To...

                      videos  \
0                        NaN
1                        NaN
2                        NaN
3                        NaN
4                        NaN
...                      ...
1991                     NaN
1992                     NaN
1993                     NaN
1994  ["pi-13889998_cae700"]
1995                     NaN

                                     seller_information  \
0                                                   NaN
1                                                   NaN
2                                                   NaN
3                                                   NaN
4     Old███. 2███162█████████o. ███████████████████...
...                                                 ...
1991  58/███15 ███AMP█████████LIP███████████████████...
1992  MIL███TAR███TAI█████████ LI███████████████████...
1993  201███WAR███H, █████████TEL███████████████████...
1994  Sho███o. ███-41█████████i T███████████████████...
1995  A-2███NOI███SEC█████████AUT███████████████████...

                  variations  \
0                       [{}]
1                       [{}]
2                    [{},{}]
3     [{},{},{},{},{},{},{}]
4           [{},{},{},{},{}]
...                      ...
1991                     NaN
1992                     NaN
1993                     NaN
1994        [{},{},{},{},{}]
1995                     NaN

                                             best_offer  \
0                                                    {}
1                                                    {}
2                                                    {}
3                                                    {}
4     {"applicable_on":"Orders above Rs. 999 (only o...
...                                                 ...
1991  {"applicable_on":"Orders above Rs. 649 (only o...
1992  {"applicable_on":"Orders above Rs. 649 (only o...
1993  {"applicable_on":"Orders above Rs. 649 (only o...
1994  {"applicable_on":"Orders above Rs. 649 (only o...
1995  {"applicable_on":"Orders above Rs. 649 (only o...

                                            more_offers   category
0     [{"offer_name":"10% Instant Discount on Citi C...  bedsheets
1     [{"offer_name":"10% Instant Discount on Citi C...  bedsheets
2     [{"offer_name":"10% Instant Discount on Citi C...  bedsheets
3     [{"offer_name":"10% Instant Discount on Citi C...  bedsheets
4     [{"offer_name":"10% Instant Discount on IndusI...  bedsheets
...                                                 ...        ...
1991  [{"offer_name":"10% Instant Discount on IndusI...     briefs
1992  [{"offer_name":"10% Instant Discount on IndusI...     briefs
1993  [{"offer_name":"10% Instant Discount on IndusI...     briefs
1994  [{"offer_name":"10% Instant Discount on IndusI...     briefs
1995  [{"offer_name":"10% Instant Discount on IndusI...     briefs

[1996 rows x 24 columns]

**#Reading csv file **

In [5]:
#Checking Columns type of each files
for file in csv_files:
    df = pd.read_csv(file)
    print("Columns:", df.columns)

Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',

In [6]:
#Exploring data (info,head,describe,tail,shape)
type(combined_df)

pandas.core.frame.DataFrame

In [7]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1996 entries, 0 to 1995
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1996 non-null   int64
 1   title                   1996 non-null   object
 2   product_description     1996 non-null   object
 3   rating                  1996 non-null   float64
 4   ratings_count           1996 non-null   int64
 5   initial_price           1996 non-null   float64
 6   discount                1754 non-null   float64
 7   final_price             1996 non-null   object
 8   currency                1996 non-null   object
 9   images                  1996 non-null   object
 10  delivery_options        1996 non-null   object
 11  product_details         1996 non-null   object
 12  breadcrumbs             1996 non-null   object
 13  product_specifications  1996 non-null   object
 14  amount_of_stars         1996 non-null   object
 15  what_customers_said     854 non-null    object
 16  seller_name             1396 non-null   object
 17  sizes                   1996 non-null   object
 18  videos                  438 non-null    object
 19  seller_information      1396 non-null   object
 20  variations              874 non-null    object
 21  best_offer              1996 non-null   object
 22  more_offers             1996 non-null   object
 23  category                1996 non-null   object
dtypes: float64(3), int64(2), object(19)
memory usage: 374.4+ KB

In [8]:
combined_df.shape

(1996, 24)

In [9]:
combined_df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [10]:
combined_df.describe()

         product_id       rating  ratings_count  initial_price     discount
count  1.996000e+03  1996.000000    1996.000000    1996.000000  1754.000000
mean   1.713339e+07     3.620591      76.746493    2725.845190    53.493158
std    3.814139e+06     1.375129     241.274882    2409.543359    18.027241
min    5.868460e+05     0.000000       0.000000     249.000000     1.000000
25%    1.511501e+07     3.700000       7.000000    1399.000000    44.000000
50%    1.820890e+07     4.100000      17.000000    1999.000000    55.500000
75%    1.902737e+07     4.300000      58.000000    3299.000000    66.000000
max    2.274707e+07     5.000000    4441.000000   22199.000000    88.000000

In [11]:
combined_df.head(10)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999.0,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
1,18602850,My Room,Ethnic Print 144 TC Super King Bedsheet with 2...,4.5,22,2999.0,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""Super King""}]",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
2,8961147,Story@home,Pink & White Floral 160 TC Cotton 1 King Bedsh...,3.7,7,2199.0,53.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/896...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Double King""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
3,8430275,MYTRIDENT,Sea Green Floral Flat 120 TC Cotton 1 Queen Be...,4.4,26,2199.0,46.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Double Queen""}]",NaN,NaN,"[{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
4,18346118,Arrabi,Pink & White Graphic 300 TC King Bedsheet with...,0.0,0,3329.0,74.0,"""₹865.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Sig███Ove███as,"[{""size"":""Super King""}]",NaN,Old███. 2███162█████████o. ███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bedsheets
5,18327434,BELLA CASA,Unisex Blue Bedsheets,0.0,0,1499.0,73.0,"""₹404.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Bel███Cas███ash█████████ail█████████,"[{""size"":""Single""}]",NaN,E-1███103███PIP█████████ IN███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bedsheets
6,18492504,ROMEE,Blue & Beige Conversational 160 TC King Bedshe...,3.9,10,3499.0,65.0,"""₹3,499.00""",INR,http://assets.myntassets.com/assets/images/184...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""Double King""}]",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
7,13729978,DDecor,White & Brown Floral 350 TC Cotton 1 King Beds...,3.6,15,1599.0,20.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Double King""}]",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
8,19788630,Home Ecstasy,140tc Pure Cotton printed Teal Blue Single Bed...,4.5,6,1199.0,42.0,"""₹1,199.00""",INR,http://assets.myntassets.com/assets/images/197...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Single""},{""size"":""Double Queen""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
9,20296382,DREAM WEAVERZ,Grey & Coral Printed 220 TC Glazed Cotton King...,3.8,18,2599.0,78.0,"""₹2,599.00""",INR,http://assets.myntassets.com/assets/images/202...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Double Queen""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets

In [12]:
combined_df.tail(6)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
1990,19206416,ABELINO,Women Set of 3 Assorted Cotton Boy Shorts Brie...,3.6,14,1899.0,80.0,"""₹379.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":2,""2_stars"":3,""3_stars"":1,""4_stars"":...",NaN,ARI███T T███ING█████████,"[{""size"":""S"",""value"":""26.0in"",""value_name"":""To...",NaN,F-2███RST███OOR█████████7VA███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs
1991,22196594,Zoiro,Men Pack Of 2 Anti-Bacterial Basic Briefs,5.0,6,499.0,NaN,"""₹499.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",J.G███OSI███ PR█████████ITE███,"[{""size"":""S"",""value"":""28.0in"",""value_name"":""To...",NaN,58/███15 ███AMP█████████LIP███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs
1992,22196914,Zivame,Women Pack Of 3 Low-Rise Ultra Soft Bikini Briefs,4.6,5,799.0,50.0,"""₹399.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,MIL███AR ███AIL█████████LIM██████,"[{""size"":""S"",""value"":""28.0in"",""value_name"":""To...",NaN,MIL███TAR███TAI█████████ LI███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs
1993,21906602,bummer,Women Printed Micro Modal Mid Rise Boy Shorts,4.6,23,599.0,25.0,"""₹449.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,BAL███APP███LS █████████IMI██████,"[{""size"":""S"",""value"":""28.0in"",""value_name"":""To...",NaN,"201███WAR███H, █████████TEL███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs
1994,13889998,XYXX,Men Grey Solid Ultra-Soft Antimicrobial Basic ...,4.1,202,249.0,NaN,"""₹249.00""",INR,http://assets.myntassets.com/assets/images/138...,...,"{""1_star"":15,""2_stars"":13,""3_stars"":20,""4_star...","[{""percentage"":""70"",""value_name"":""Fit, Just Ri...",XYX███PPA███S P█████████MIT████████████,"[{""size"":""S"",""value"":""28.0in to 30.0in"",""value...","[""pi-13889998_cae700""]",Sho███o. ███-41█████████i T███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs
1995,22436508,Bruchi CLUB,Men Low-Rise Anti-Bacterial Basic Briefs,5.0,4,888.0,65.0,"""₹310.00""",INR,http://assets.myntassets.com/assets/images/224...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",BRU███ CL███APP█████████ATE█████████,"[{""size"":""S"",""value"":""28.0in"",""value_name"":""To...",NaN,A-2███NOI███SEC█████████AUT███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs

In [13]:
#identifying null values
combined_df.isnull().sum()

product_id                   0
title                        0
product_description          0
rating                       0
ratings_count                0
initial_price                0
discount                   242
final_price                  0
currency                     0
images                       0
delivery_options             0
product_details              0
breadcrumbs                  0
product_specifications       0
amount_of_stars              0
what_customers_said       1142
seller_name                600
sizes                        0
videos                    1558
seller_information         600
variations                1122
best_offer                   0
more_offers                  0
category                     0
dtype: int64

In [14]:
combined_df.fillna({"price":0, "category":"Unknown"})

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999.0,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
1,18602850,My Room,Ethnic Print 144 TC Super King Bedsheet with 2...,4.5,22,2999.0,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""Super King""}]",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
2,8961147,Story@home,Pink & White Floral 160 TC Cotton 1 King Bedsh...,3.7,7,2199.0,53.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/896...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Double King""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
3,8430275,MYTRIDENT,Sea Green Floral Flat 120 TC Cotton 1 Queen Be...,4.4,26,2199.0,46.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Double Queen""}]",NaN,NaN,"[{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
4,18346118,Arrabi,Pink & White Graphic 300 TC King Bedsheet with...,0.0,0,3329.0,74.0,"""₹865.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Sig███Ove███as,"[{""size"":""Super King""}]",NaN,Old███. 2███162█████████o. ███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bedsheets
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1991,22196594,Zoiro,Men Pack Of 2 Anti-Bacterial Basic Briefs,5.0,6,499.0,NaN,"""₹499.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",J.G███OSI███ PR█████████ITE███,"[{""size"":""S"",""value"":""28.0in"",""value_name"":""To...",NaN,58/███15 ███AMP█████████LIP███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs
1992,22196914,Zivame,Women Pack Of 3 Low-Rise Ultra Soft Bikini Briefs,4.6,5,799.0,50.0,"""₹399.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,MIL███AR ███AIL█████████LIM██████,"[{""size"":""S"",""value"":""28.0in"",""value_name"":""To...",NaN,MIL███TAR███TAI█████████ LI███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs
1993,21906602,bummer,Women Printed Micro Modal Mid Rise Boy Shorts,4.6,23,599.0,25.0,"""₹449.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,BAL███APP███LS █████████IMI██████,"[{""size"":""S"",""value"":""28.0in"",""value_name"":""To...",NaN,"201███WAR███H, █████████TEL███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs
1994,13889998,XYXX,Men Grey Solid Ultra-Soft Antimicrobial Basic ...,4.1,202,249.0,NaN,"""₹249.00""",INR,http://assets.myntassets.com/assets/images/138...,...,"{""1_star"":15,""2_stars"":13,""3_stars"":20,""4_star...","[{""percentage"":""70"",""value_name"":""Fit, Just Ri...",XYX███PPA███S P█████████MIT████████████,"[{""size"":""S"",""value"":""28.0in to 30.0in"",""value...","[""pi-13889998_cae700""]",Sho███o. ███-41█████████i T███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs
1995,22436508,Bruchi CLUB,Men Low-Rise Anti-Bacterial Basic Briefs,5.0,4,888.0,65.0,"""₹310.00""",INR,http://assets.myntassets.com/assets/images/224...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",BRU███ CL███APP█████████ATE█████████,"[{""size"":""S"",""value"":""28.0in"",""value_name"":""To...",NaN,A-2███NOI███SEC█████████AUT███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs

In [15]:
combined_df = combined_df.drop_duplicates()
combined_df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999.0,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
1,18602850,My Room,Ethnic Print 144 TC Super King Bedsheet with 2...,4.5,22,2999.0,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""Super King""}]",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
2,8961147,Story@home,Pink & White Floral 160 TC Cotton 1 King Bedsh...,3.7,7,2199.0,53.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/896...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Double King""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
3,8430275,MYTRIDENT,Sea Green Floral Flat 120 TC Cotton 1 Queen Be...,4.4,26,2199.0,46.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Double Queen""}]",NaN,NaN,"[{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
4,18346118,Arrabi,Pink & White Graphic 300 TC King Bedsheet with...,0.0,0,3329.0,74.0,"""₹865.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Sig███Ove███as,"[{""size"":""Super King""}]",NaN,Old███. 2███162█████████o. ███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bedsheets
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890.0,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
1028,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900.0,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
1029,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950.0,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
1030,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295.0,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
1031,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699.0,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [16]:
filtered_df = combined_df[combined_df["initial_price"] < 2000]
filtered_df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
5,18327434,BELLA CASA,Unisex Blue Bedsheets,0.0,0,1499.0,73.0,"""₹404.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Bel███Cas███ash█████████ail█████████,"[{""size"":""Single""}]",NaN,E-1███103███PIP█████████ IN███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bedsheets
7,13729978,DDecor,White & Brown Floral 350 TC Cotton 1 King Beds...,3.6,15,1599.0,20.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Double King""}]",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
8,19788630,Home Ecstasy,140tc Pure Cotton printed Teal Blue Single Bed...,4.5,6,1199.0,42.0,"""₹1,199.00""",INR,http://assets.myntassets.com/assets/images/197...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Single""},{""size"":""Double Queen""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
11,16299490,Bodycare Kids,Bodycare Boys Pack Of 6 Assorted Cotton Ben 10...,3.8,10,978.0,NaN,"""₹978.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,BOD███RE ███ERN█████████IMI██████,"[{""size"":""5-6Y"",""value"":""17.0in"",""value_name"":...",NaN,"D-2███13,███cto█████████tar███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",innerwear-vests
12,22429820,YK Basics,Boys Pack of 5 Solid Pure Cotton Innerwear Vests,3.5,12,1299.0,61.0,"""₹532.00""",INR,http://assets.myntassets.com/assets/images/224...,...,"{""1_star"":3,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Home,"[{""size"":""6-12M"",""value"":""12.4in"",""value_name""...",NaN,Hom███and███B/1█████████ Am███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",innerwear-vests
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1012,18864968,Lavie,Glossy Sacy Women Pink Animal Textured Zip Aro...,4.4,21,1999.0,65.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/188...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""L""}]","[""rw-18864968_cae700""]",NaN,"[{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",wallets
1018,17697474,Timex,Women White Dial & Gold Toned Analogue Watch T...,4.9,8,1995.0,20.0,"""₹1,596.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,TIM███T R███IL █████████RIV████████████,"[{""size"":""Onesize""}]",NaN,"Fla███o. ███, 6█████████y C███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",watches
1019,7349545,Fantasy World,Unisex Grey Digital Watch,3.7,119,499.0,20.0,"""₹499.00""",INR,http://assets.myntassets.com/assets/images/734...,...,"{""1_star"":20,""2_stars"":8,""3_stars"":13,""4_stars...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-7349545_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
1025,19322504,V2A,Girls Blue Printed Dial & Pink Straps Digital ...,4.0,6,1599.0,50.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/193...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Br ███erp███es,"[{""size"":""Onesize""}]",NaN,Kha███ no███122█████████lhi██████████████████,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
1031,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699.0,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [17]:
selected_df = combined_df[["product_id", "title", "category", "final_price", "discount"]]
selected_df

      product_id       title   category   final_price  discount
0       18602872     My Room  bedsheets   "₹2,999.00"      54.0
1       18602850     My Room  bedsheets   "₹2,999.00"      54.0
2        8961147  Story@home  bedsheets   "₹2,199.00"      53.0
3        8430275   MYTRIDENT  bedsheets   "₹2,199.00"      46.0
4       18346118      Arrabi  bedsheets     "₹865.00"      74.0
...          ...         ...        ...           ...       ...
1027    13698258       KREDO    watches  "₹11,890.00"      50.0
1028    16896006       GUESS    watches   "₹8,900.00"      45.0
1029     1708108    GIORDANO    watches   "₹7,950.00"      50.0
1030    19280114    Fastrack    watches   "₹2,636.00"      20.0
1031    18601682     BOLDFIT  yoga-mats     "₹699.00"      31.0

[1000 rows x 5 columns]

In [18]:
combined_df["quantity"] = 1
combined_df["total_amount"] = combined_df["initial_price"] * 1

In [19]:
combined_df.to_csv("cleaned_dataset.csv", index=False)
df=pd.read_csv('cleaned_dataset.csv')
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity,total_amount
0,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999.0,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,NaN,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets,1,2999.0
1,18602850,My Room,Ethnic Print 144 TC Super King Bedsheet with 2...,4.5,22,2999.0,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,NaN,"[{""size"":""Super King""}]",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets,1,2999.0
2,8961147,Story@home,Pink & White Floral 160 TC Cotton 1 King Bedsh...,3.7,7,2199.0,53.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/896...,...,NaN,"[{""size"":""Double King""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets,1,2199.0
3,8430275,MYTRIDENT,Sea Green Floral Flat 120 TC Cotton 1 Queen Be...,4.4,26,2199.0,46.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,NaN,"[{""size"":""Double Queen""}]",NaN,NaN,"[{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets,1,2199.0
4,18346118,Arrabi,Pink & White Graphic 300 TC King Bedsheet with...,0.0,0,3329.0,74.0,"""₹865.00""",INR,http://assets.myntassets.com/assets/images/183...,...,Sig███Ove███as,"[{""size"":""Super King""}]",NaN,Old███. 2███162█████████o. ███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bedsheets,1,3329.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890.0,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,1,11890.0
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900.0,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,1,8900.0
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950.0,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,1,7950.0
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295.0,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,1,3295.0
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699.0,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats,1,699.0

**Loaded CSV 
Checked Datatype of each Columns
Explored data 
Handled missing data
Stored Cleaned CSV**

In [20]:
#verifying 
print("="*40)
print("ASSIGNMENT VERIFICATION REPORT")
print("="*40)

print(f"\n Rows loaded: {combined_df.shape[0]}")
print(f" Columns: {combined_df.shape[1]}")
print(f" Duplicates remaining: {combined_df.duplicated().sum()}")
print(f" Nulls in price: {combined_df['initial_price'].isnull().sum()}")
print(f" Nulls in category: {combined_df['category'].isnull().sum()}")
print(f" total_amount dtype: {combined_df['total_amount'].dtype}")
print(f" total_amount correct: {(combined_df['total_amount'] == combined_df['initial_price'] * combined_df['quantity']).all()}")
print(f" CSV saved: {os.path.exists('cleaned_dataset.csv')}")

========================================
ASSIGNMENT VERIFICATION REPORT
========================================

 Rows loaded: 1000
 Columns: 26
 Duplicates remaining: 0
 Nulls in price: 0
 Nulls in category: 0
 total_amount dtype: float64
 total_amount correct: True
 CSV saved: True